jwt:
  signing-key: 62163471-bc17-45f2-bfcf-a938a884f81a
  expires-time: 1d
  buffer-time: 1d
  issuer: xiaozhou

mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name:  hrm
  username: root
  password: 123456
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: silent
  log-zap: true

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""

system:
  env: public
  addr: 9999
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  router-prefix: ""

zap:
  level: info   #//输出级别
  prefix: '[github.com/zhou-Qingzhang/hrm]'
  format: console
  director: ./logs
  encode-level: LowercaseColorLevelEncoder  #// 小写编码器带颜色
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

cors:
  allow-origin: "*" # 允许跨域的域名, 多个用逗号分隔, 如: "http://localhost, http://
  allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
  allow-methods: POST, GET
  expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
  allow-credentials: true # 布尔值
